nc=input('coloque o nome do colaborador: ')
vh=float(input('coloque o valor da hora trabalhada: '))
ht=float(input('coloque as horas trabalhadas: '))
vb=float(input('coloque o valor do bônus fixo do mês: '))
print("colaborador",nc,"recebe um valor bruto de:",vh*ht,"e um valor liquido de:",vh*ht+vb)
